// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VisualBasicWinFormsCoreApp.Data.Entities
{
    public partial class func_get_country_totalsResult
    {
        public string Country { get; set; }
        public DateTime? OrderDate { get; set; }
        public float? DayTotal { get; set; }
        public int? Year { get; set; }
        public double? DayTotalAmount { get; set; }
        public double? YearAmount { get; set; }
        public double? CountryTotal { get; set; }
        public double? RunningTotal { get; set; }
    }
}
