// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using VisualBasicWinFormsCoreApp.Data.Entities;

namespace VisualBasicWinFormsCoreApp.Data.Entities
{
    public partial class NorthwindContext
    {

        [DbFunction("func_get_country_totals", "dbo")]
        public IQueryable<func_get_country_totalsResult> func_get_country_totals()
        {
            return FromExpression(() => func_get_country_totals());
        }

        [DbFunction("func_RoundNumber", "dbo")]
        public static decimal? func_RoundNumber(decimal? number, int? decpoint)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<func_get_country_totalsResult>().HasNoKey();
        }
    }
}
